/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *image8;
  GtkWidget *button2;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label6;
  GtkWidget *button1;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image9;
  GtkWidget *label23;
  GtkWidget *image7;
  GtkWidget *label7;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 512, 80);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 512, 144);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label2 = gtk_label_new (_("password"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 264, 144);
  gtk_widget_set_size_request (label2, 176, 32);

  label1 = gtk_label_new (_("username"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 264, 80);
  gtk_widget_set_size_request (label1, 176, 32);

  image8 = create_pixmap (window1, "gym.jpeg");
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed1), image8, 88, 24);
  gtk_widget_set_size_request (image8, 184, 160);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 648, 256);
  gtk_widget_set_size_request (button2, 64, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button2), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Quit"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox1), label6, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 472, 200);
  gtk_widget_set_size_request (button1, 120, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button1), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox7), image9, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("log in "));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox7), label23, FALSE, FALSE, 0);

  image7 = create_pixmap (window1, "index.jpeg");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed1), image7, 400, 312);
  gtk_widget_set_size_request (image7, 336, 144);

  label7 = gtk_label_new (_("Bienvenue dans my Gym"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 424, 16);
  gtk_widget_set_size_request (label7, 240, 40);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window1, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, label23, "label23");
  GLADE_HOOKUP_OBJECT (window1, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *label3;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));
  gtk_window_set_position (GTK_WINDOW (window2), GTK_WIN_POS_CENTER);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  label3 = gtk_label_new (_("bienvenue dans l'espace nutritionniste"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 88, 104);
  gtk_widget_set_size_request (label3, 232, 48);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, label3, "label3");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed3;
  GtkWidget *label4;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));
  gtk_window_set_position (GTK_WINDOW (window3), GTK_WIN_POS_CENTER);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  label4 = gtk_label_new (_("bienvenue dans l'espace coach"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 104, 96);
  gtk_widget_set_size_request (label4, 240, 120);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, label4, "label4");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed4;
  GtkWidget *notebook1;
  GtkWidget *fixed12;
  GtkWidget *espace_adherants;
  GtkWidget *adherant_comboboxentry1;
  GtkWidget *rdv_adherant;
  GtkWidget *consulter_cours_adherant;
  GtkWidget *adherant_button12;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image14;
  GtkWidget *label48;
  GtkWidget *inf_per_aderant;
  GtkWidget *adherant_button13;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image15;
  GtkWidget *label50;
  GtkWidget *adherant_button14;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image16;
  GtkWidget *label51;
  GtkWidget *espace_adherants;
  GtkWidget *fixed13;
  GtkWidget *adherant_entry11;
  GtkWidget *adherant_entry12;
  GtkObject *adherant_spinbutton4_adj;
  GtkWidget *adherant_spinbutton4;
  GtkObject *adherant_spinbutton5_adj;
  GtkWidget *adherant_spinbutton5;
  GtkWidget *info_per;
  GtkWidget *adherant_label53;
  GtkWidget *adherant_label54;
  GtkWidget *adherant_label55;
  GtkWidget *adherant_button15;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image17;
  GtkWidget *label56;
  GtkWidget *adherant_button16;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image18;
  GtkWidget *label57;
  GtkWidget *informations_personnelles;
  GtkWidget *fixed14;
  GtkObject *adherant_spinbutton6_adj;
  GtkWidget *adherant_spinbutton6;
  GtkObject *adherant_spinbutton7_adj;
  GtkWidget *adherant_spinbutton7;
  GtkObject *adherant_spinbutton8_adj;
  GtkWidget *adherant_spinbutton8;
  GtkWidget *adherant_label58;
  GtkWidget *adherant_label59;
  GtkWidget *adherant_comboboxentry2;
  GtkWidget *adherant_button17;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image19;
  GtkWidget *label60;
  GtkWidget *badherant_button18;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image20;
  GtkWidget *label61;
  GtkWidget *adherant_button19;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image21;
  GtkWidget *label62;
  GtkWidget *rdv_med;
  GtkWidget *fixed15;
  GtkWidget *adherant_label64;
  GtkObject *adherant_spinbutton9_adj;
  GtkWidget *adherant_spinbutton9;
  GtkObject *adherant_spinbutton10_adj;
  GtkWidget *adherant_spinbutton10;
  GtkObject *adherant_spinbutton11_adj;
  GtkWidget *adherant_spinbutton11;
  GtkWidget *adherant_label63;
  GtkWidget *adherant_comboboxentry3;
  GtkWidget *adherant_button20;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image22;
  GtkWidget *label65;
  GtkWidget *adherant_button21;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image23;
  GtkWidget *label66;
  GtkWidget *adherant_button22;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image24;
  GtkWidget *label67;
  GtkWidget *rdv_kine;
  GtkWidget *fixed16;
  GtkObject *adherant_spinbutton12_adj;
  GtkWidget *adherant_spinbutton12;
  GtkObject *adherant_spinbutton13_adj;
  GtkWidget *adherant_spinbutton13;
  GtkObject *adherant_spinbutton14_adj;
  GtkWidget *adherant_spinbutton14;
  GtkWidget *adherant_label68;
  GtkWidget *adherant_label69;
  GtkWidget *adherant_comboboxentry4;
  GtkWidget *adherant_button23;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image25;
  GtkWidget *label70;
  GtkWidget *adherant_button24;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image26;
  GtkWidget *label71;
  GtkWidget *adherant_button25;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image27;
  GtkWidget *label72;
  GtkWidget *rdv_diet;
  GtkWidget *fixed17;
  GtkObject *adherant_spinbutton15_adj;
  GtkWidget *adherant_spinbutton15;
  GtkObject *adherant_spinbutton16_adj;
  GtkWidget *adherant_spinbutton16;
  GtkObject *adherant_spinbutton17_adj;
  GtkWidget *adherant_spinbutton17;
  GtkWidget *adherant_label73;
  GtkWidget *adherant_label74;
  GtkWidget *adherant_comboboxentry5;
  GtkWidget *adherant_button26;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image28;
  GtkWidget *label75;
  GtkWidget *adherant_button27;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image29;
  GtkWidget *label76;
  GtkWidget *adherant_button28;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image30;
  GtkWidget *label77;
  GtkWidget *rdv_coach;
  GtkWidget *fixed18;
  GtkWidget *adherant_label80;
  GtkWidget *adherant_treeview1;
  GtkWidget *adherant_button29;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image31;
  GtkWidget *label82;
  GtkWidget *planning_cours;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));
  gtk_window_set_position (GTK_WINDOW (window4), GTK_WIN_POS_CENTER);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window4), fixed4);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed4), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 696, 400);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed12);

  espace_adherants = gtk_label_new_with_mnemonic (_("espace adherants"));
  gtk_widget_show (espace_adherants);
  gtk_fixed_put (GTK_FIXED (fixed12), espace_adherants, 0, 8);
  gtk_widget_set_size_request (espace_adherants, 568, 16);
  gtk_label_set_use_markup (GTK_LABEL (espace_adherants), TRUE);

  adherant_comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (adherant_comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed12), adherant_comboboxentry1, 232, 64);
  gtk_widget_set_size_request (adherant_comboboxentry1, 189, 29);
  gtk_container_set_border_width (GTK_CONTAINER (adherant_comboboxentry1), 4);
  gtk_combo_box_append_text (GTK_COMBO_BOX (adherant_comboboxentry1), _("medecin nutritionniste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (adherant_comboboxentry1), _("dieteticien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (adherant_comboboxentry1), _("kinesitherapeute"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (adherant_comboboxentry1), _("coach"));

  rdv_adherant = gtk_label_new (_("prendre un rendez-vous:"));
  gtk_widget_show (rdv_adherant);
  gtk_fixed_put (GTK_FIXED (fixed12), rdv_adherant, 0, 64);
  gtk_widget_set_size_request (rdv_adherant, 184, 32);
  gtk_label_set_use_markup (GTK_LABEL (rdv_adherant), TRUE);

  consulter_cours_adherant = gtk_label_new (_("Consulter le planning des cours :"));
  gtk_widget_show (consulter_cours_adherant);
  gtk_fixed_put (GTK_FIXED (fixed12), consulter_cours_adherant, 0, 136);
  gtk_widget_set_size_request (consulter_cours_adherant, 240, 40);
  gtk_label_set_use_markup (GTK_LABEL (consulter_cours_adherant), TRUE);

  adherant_button12 = gtk_button_new ();
  gtk_widget_show (adherant_button12);
  gtk_fixed_put (GTK_FIXED (fixed12), adherant_button12, 320, 136);
  gtk_widget_set_size_request (adherant_button12, 120, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (adherant_button12), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image14 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox12), image14, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("le planning"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox12), label48, FALSE, FALSE, 0);

  inf_per_aderant = gtk_label_new (_("modifier vos informations personnelles:"));
  gtk_widget_show (inf_per_aderant);
  gtk_fixed_put (GTK_FIXED (fixed12), inf_per_aderant, 0, 224);
  gtk_widget_set_size_request (inf_per_aderant, 288, 32);
  gtk_label_set_use_markup (GTK_LABEL (inf_per_aderant), TRUE);

  adherant_button13 = gtk_button_new ();
  gtk_widget_show (adherant_button13);
  gtk_fixed_put (GTK_FIXED (fixed12), adherant_button13, 368, 224);
  gtk_widget_set_size_request (adherant_button13, 96, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (adherant_button13), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image15 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox13), image15, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox13), label50, FALSE, FALSE, 0);

  adherant_button14 = gtk_button_new ();
  gtk_widget_show (adherant_button14);
  gtk_fixed_put (GTK_FIXED (fixed12), adherant_button14, 184, 288);
  gtk_widget_set_size_request (adherant_button14, 168, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (adherant_button14), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image16 = gtk_image_new_from_stock ("gtk-disconnect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox14), image16, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("se deconnecter"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox14), label51, FALSE, FALSE, 0);

  espace_adherants = gtk_label_new (_("espace_adherants"));
  gtk_widget_show (espace_adherants);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), espace_adherants);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed13);

  adherant_entry11 = gtk_entry_new ();
  gtk_widget_show (adherant_entry11);
  gtk_fixed_put (GTK_FIXED (fixed13), adherant_entry11, 192, 152);
  gtk_widget_set_size_request (adherant_entry11, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (adherant_entry11), _("6666666"));
  gtk_entry_set_invisible_char (GTK_ENTRY (adherant_entry11), 8226);

  adherant_entry12 = gtk_entry_new ();
  gtk_widget_show (adherant_entry12);
  gtk_fixed_put (GTK_FIXED (fixed13), adherant_entry12, 192, 184);
  gtk_widget_set_size_request (adherant_entry12, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (adherant_entry12), _("mmm@esprit.tn"));
  gtk_entry_set_invisible_char (GTK_ENTRY (adherant_entry12), 8226);

  adherant_spinbutton4_adj = gtk_adjustment_new (150, 50, 250, 1, 10, 10);
  adherant_spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton4_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed13), adherant_spinbutton4, 192, 224);
  gtk_widget_set_size_request (adherant_spinbutton4, 160, 24);

  adherant_spinbutton5_adj = gtk_adjustment_new (20, 15, 250, 1, 10, 10);
  adherant_spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton5_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed13), adherant_spinbutton5, 192, 256);
  gtk_widget_set_size_request (adherant_spinbutton5, 160, 24);

  info_per = gtk_label_new (_("informations personnelles"));
  gtk_widget_show (info_per);
  gtk_fixed_put (GTK_FIXED (fixed13), info_per, 0, 8);
  gtk_widget_set_size_request (info_per, 616, 16);
  gtk_label_set_use_markup (GTK_LABEL (info_per), TRUE);

  adherant_label53 = gtk_label_new (_("Nom:\nPrenom:\ndate de naissance:\nnumero de CIN:\nnumero d'abonnement:"));
  gtk_widget_show (adherant_label53);
  gtk_fixed_put (GTK_FIXED (fixed13), adherant_label53, 32, 24);
  gtk_widget_set_size_request (adherant_label53, 232, 136);
  gtk_label_set_use_markup (GTK_LABEL (adherant_label53), TRUE);

  adherant_label54 = gtk_label_new (_("**********\n**********\n**********\n*********\n*********"));
  gtk_widget_show (adherant_label54);
  gtk_fixed_put (GTK_FIXED (fixed13), adherant_label54, 256, 40);
  gtk_widget_set_size_request (adherant_label54, 184, 104);
  gtk_label_set_use_markup (GTK_LABEL (adherant_label54), TRUE);

  adherant_label55 = gtk_label_new (_("numero de telephone:\n\nadresse e-mail:\n\ntaille:\n\npoids:\n\n"));
  gtk_widget_show (adherant_label55);
  gtk_fixed_put (GTK_FIXED (fixed13), adherant_label55, 16, 160);
  gtk_widget_set_size_request (adherant_label55, 176, 152);
  gtk_label_set_use_markup (GTK_LABEL (adherant_label55), TRUE);

  adherant_button15 = gtk_button_new ();
  gtk_widget_show (adherant_button15);
  gtk_fixed_put (GTK_FIXED (fixed13), adherant_button15, 192, 312);
  gtk_widget_set_size_request (adherant_button15, 136, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (adherant_button15), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image17 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox15), image17, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox15), label56, FALSE, FALSE, 0);

  adherant_button16 = gtk_button_new ();
  gtk_widget_show (adherant_button16);
  gtk_fixed_put (GTK_FIXED (fixed13), adherant_button16, 376, 176);
  gtk_widget_set_size_request (adherant_button16, 232, 64);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (adherant_button16), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image18 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox16), image18, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("enregistrer les modifications"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox16), label57, FALSE, FALSE, 0);

  informations_personnelles = gtk_label_new (_("informations_personnelles"));
  gtk_widget_show (informations_personnelles);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), informations_personnelles);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed14);

  adherant_spinbutton6_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  adherant_spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton6_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed14), adherant_spinbutton6, 104, 104);
  gtk_widget_set_size_request (adherant_spinbutton6, 60, 27);

  adherant_spinbutton7_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  adherant_spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton7_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed14), adherant_spinbutton7, 272, 104);
  gtk_widget_set_size_request (adherant_spinbutton7, 60, 27);

  adherant_spinbutton8_adj = gtk_adjustment_new (2018, 2018, 2030, 1, 10, 10);
  adherant_spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton8_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed14), adherant_spinbutton8, 440, 104);
  gtk_widget_set_size_request (adherant_spinbutton8, 60, 27);

  adherant_label58 = gtk_label_new (_("rendez-vous et disponibilite des medecins nutritionnistes"));
  gtk_widget_show (adherant_label58);
  gtk_fixed_put (GTK_FIXED (fixed14), adherant_label58, 0, 8);
  gtk_widget_set_size_request (adherant_label58, 616, 16);
  gtk_label_set_use_markup (GTK_LABEL (adherant_label58), TRUE);

  adherant_label59 = gtk_label_new (_("selectionner la date du rendez-vous"));
  gtk_widget_show (adherant_label59);
  gtk_fixed_put (GTK_FIXED (fixed14), adherant_label59, 136, 48);
  gtk_widget_set_size_request (adherant_label59, 328, 40);
  gtk_label_set_use_markup (GTK_LABEL (adherant_label59), TRUE);

  adherant_comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (adherant_comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed14), adherant_comboboxentry2, 32, 176);
  gtk_widget_set_size_request (adherant_comboboxentry2, 213, 29);

  adherant_button17 = gtk_button_new ();
  gtk_widget_show (adherant_button17);
  gtk_fixed_put (GTK_FIXED (fixed14), adherant_button17, 352, 176);
  gtk_widget_set_size_request (adherant_button17, 112, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (adherant_button17), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image19 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox17), image19, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox17), label60, FALSE, FALSE, 0);

  badherant_button18 = gtk_button_new ();
  gtk_widget_show (badherant_button18);
  gtk_fixed_put (GTK_FIXED (fixed14), badherant_button18, 160, 248);
  gtk_widget_set_size_request (badherant_button18, 280, 37);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (badherant_button18), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image20 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox18), image20, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("prendre rendez-vous"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox18), label61, FALSE, FALSE, 0);

  adherant_button19 = gtk_button_new ();
  gtk_widget_show (adherant_button19);
  gtk_fixed_put (GTK_FIXED (fixed14), adherant_button19, 32, 312);
  gtk_widget_set_size_request (adherant_button19, 106, 37);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (adherant_button19), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image21 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox19), image21, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox19), label62, FALSE, FALSE, 0);

  rdv_med = gtk_label_new (_("rdv_med"));
  gtk_widget_show (rdv_med);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), rdv_med);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed15);

  adherant_label64 = gtk_label_new (_("selectionner la date du rendez-vous"));
  gtk_widget_show (adherant_label64);
  gtk_fixed_put (GTK_FIXED (fixed15), adherant_label64, 112, 56);
  gtk_widget_set_size_request (adherant_label64, 376, 40);
  gtk_label_set_use_markup (GTK_LABEL (adherant_label64), TRUE);

  adherant_spinbutton9_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  adherant_spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton9_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed15), adherant_spinbutton9, 96, 120);
  gtk_widget_set_size_request (adherant_spinbutton9, 60, 27);

  adherant_spinbutton10_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  adherant_spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton10_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed15), adherant_spinbutton10, 264, 120);
  gtk_widget_set_size_request (adherant_spinbutton10, 60, 27);

  adherant_spinbutton11_adj = gtk_adjustment_new (2018, 2018, 2030, 1, 10, 10);
  adherant_spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton11_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed15), adherant_spinbutton11, 448, 120);
  gtk_widget_set_size_request (adherant_spinbutton11, 60, 27);

  adherant_label63 = gtk_label_new (_("rendez-vous et disponibilite des kinesitherapeutes"));
  gtk_widget_show (adherant_label63);
  gtk_fixed_put (GTK_FIXED (fixed15), adherant_label63, 0, 8);
  gtk_widget_set_size_request (adherant_label63, 632, 16);
  gtk_label_set_use_markup (GTK_LABEL (adherant_label63), TRUE);

  adherant_comboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (adherant_comboboxentry3);
  gtk_fixed_put (GTK_FIXED (fixed15), adherant_comboboxentry3, 16, 192);
  gtk_widget_set_size_request (adherant_comboboxentry3, 229, 29);

  adherant_button20 = gtk_button_new ();
  gtk_widget_show (adherant_button20);
  gtk_fixed_put (GTK_FIXED (fixed15), adherant_button20, 352, 184);
  gtk_widget_set_size_request (adherant_button20, 136, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (adherant_button20), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image22 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox20), image22, FALSE, FALSE, 0);

  label65 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox20), label65, FALSE, FALSE, 0);

  adherant_button21 = gtk_button_new ();
  gtk_widget_show (adherant_button21);
  gtk_fixed_put (GTK_FIXED (fixed15), adherant_button21, 176, 264);
  gtk_widget_set_size_request (adherant_button21, 248, 32);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (adherant_button21), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox21), image23, FALSE, FALSE, 0);

  label66 = gtk_label_new_with_mnemonic (_("prendre un rendez-vous"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox21), label66, FALSE, FALSE, 0);

  adherant_button22 = gtk_button_new ();
  gtk_widget_show (adherant_button22);
  gtk_fixed_put (GTK_FIXED (fixed15), adherant_button22, 40, 328);
  gtk_widget_set_size_request (adherant_button22, 130, 29);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (adherant_button22), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image24 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox22), image24, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox22), label67, FALSE, FALSE, 0);

  rdv_kine = gtk_label_new (_("rdv_kine"));
  gtk_widget_show (rdv_kine);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), rdv_kine);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed16);

  adherant_spinbutton12_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  adherant_spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton12_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton12);
  gtk_fixed_put (GTK_FIXED (fixed16), adherant_spinbutton12, 80, 128);
  gtk_widget_set_size_request (adherant_spinbutton12, 60, 27);

  adherant_spinbutton13_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  adherant_spinbutton13 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton13_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton13);
  gtk_fixed_put (GTK_FIXED (fixed16), adherant_spinbutton13, 264, 128);
  gtk_widget_set_size_request (adherant_spinbutton13, 60, 27);

  adherant_spinbutton14_adj = gtk_adjustment_new (2018, 2018, 2030, 1, 10, 10);
  adherant_spinbutton14 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton14_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton14);
  gtk_fixed_put (GTK_FIXED (fixed16), adherant_spinbutton14, 456, 128);
  gtk_widget_set_size_request (adherant_spinbutton14, 60, 27);

  adherant_label68 = gtk_label_new (_("rendez-vous et disponibilite des dieteticiens"));
  gtk_widget_show (adherant_label68);
  gtk_fixed_put (GTK_FIXED (fixed16), adherant_label68, 0, 8);
  gtk_widget_set_size_request (adherant_label68, 616, 16);
  gtk_label_set_use_markup (GTK_LABEL (adherant_label68), TRUE);

  adherant_label69 = gtk_label_new (_("selectionner la date du rendez-vous "));
  gtk_widget_show (adherant_label69);
  gtk_fixed_put (GTK_FIXED (fixed16), adherant_label69, 120, 56);
  gtk_widget_set_size_request (adherant_label69, 352, 40);
  gtk_label_set_use_markup (GTK_LABEL (adherant_label69), TRUE);

  adherant_comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (adherant_comboboxentry4);
  gtk_fixed_put (GTK_FIXED (fixed16), adherant_comboboxentry4, 32, 208);
  gtk_widget_set_size_request (adherant_comboboxentry4, 221, 29);

  adherant_button23 = gtk_button_new ();
  gtk_widget_show (adherant_button23);
  gtk_fixed_put (GTK_FIXED (fixed16), adherant_button23, 384, 208);
  gtk_widget_set_size_request (adherant_button23, 106, 29);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (adherant_button23), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image25 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox23), image25, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox23), label70, FALSE, FALSE, 0);

  adherant_button24 = gtk_button_new ();
  gtk_widget_show (adherant_button24);
  gtk_fixed_put (GTK_FIXED (fixed16), adherant_button24, 176, 272);
  gtk_widget_set_size_request (adherant_button24, 248, 40);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (adherant_button24), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image26 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox24), image26, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("prendre rendez-vous"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox24), label71, FALSE, FALSE, 0);

  adherant_button25 = gtk_button_new ();
  gtk_widget_show (adherant_button25);
  gtk_fixed_put (GTK_FIXED (fixed16), adherant_button25, 48, 328);
  gtk_widget_set_size_request (adherant_button25, 98, 29);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (adherant_button25), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image27 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox25), image27, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox25), label72, FALSE, FALSE, 0);

  rdv_diet = gtk_label_new (_("rdv_diet"));
  gtk_widget_show (rdv_diet);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), rdv_diet);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed17);

  adherant_spinbutton15_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  adherant_spinbutton15 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton15_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton15);
  gtk_fixed_put (GTK_FIXED (fixed17), adherant_spinbutton15, 88, 128);
  gtk_widget_set_size_request (adherant_spinbutton15, 60, 27);

  adherant_spinbutton16_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  adherant_spinbutton16 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton16_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton16);
  gtk_fixed_put (GTK_FIXED (fixed17), adherant_spinbutton16, 272, 128);
  gtk_widget_set_size_request (adherant_spinbutton16, 60, 27);

  adherant_spinbutton17_adj = gtk_adjustment_new (2018, 2018, 2018, 1, 10, 10);
  adherant_spinbutton17 = gtk_spin_button_new (GTK_ADJUSTMENT (adherant_spinbutton17_adj), 1, 0);
  gtk_widget_show (adherant_spinbutton17);
  gtk_fixed_put (GTK_FIXED (fixed17), adherant_spinbutton17, 464, 128);
  gtk_widget_set_size_request (adherant_spinbutton17, 60, 27);

  adherant_label73 = gtk_label_new (_("rendez-vous et disponibilite des coachs"));
  gtk_widget_show (adherant_label73);
  gtk_fixed_put (GTK_FIXED (fixed17), adherant_label73, -8, 9);
  gtk_widget_set_size_request (adherant_label73, 632, 16);
  gtk_label_set_use_markup (GTK_LABEL (adherant_label73), TRUE);

  adherant_label74 = gtk_label_new (_("selectionner la date du rendez-vous"));
  gtk_widget_show (adherant_label74);
  gtk_fixed_put (GTK_FIXED (fixed17), adherant_label74, 160, 56);
  gtk_widget_set_size_request (adherant_label74, 296, 64);
  gtk_label_set_use_markup (GTK_LABEL (adherant_label74), TRUE);

  adherant_comboboxentry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (adherant_comboboxentry5);
  gtk_fixed_put (GTK_FIXED (fixed17), adherant_comboboxentry5, 8, 200);
  gtk_widget_set_size_request (adherant_comboboxentry5, 237, 29);

  adherant_button26 = gtk_button_new ();
  gtk_widget_show (adherant_button26);
  gtk_fixed_put (GTK_FIXED (fixed17), adherant_button26, 352, 192);
  gtk_widget_set_size_request (adherant_button26, 130, 29);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (adherant_button26), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image28 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox26), image28, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox26), label75, FALSE, FALSE, 0);

  adherant_button27 = gtk_button_new ();
  gtk_widget_show (adherant_button27);
  gtk_fixed_put (GTK_FIXED (fixed17), adherant_button27, 160, 264);
  gtk_widget_set_size_request (adherant_button27, 264, 32);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (adherant_button27), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image29 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox27), image29, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("prendre un rendez-vous"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox27), label76, FALSE, FALSE, 0);

  adherant_button28 = gtk_button_new ();
  gtk_widget_show (adherant_button28);
  gtk_fixed_put (GTK_FIXED (fixed17), adherant_button28, 48, 328);
  gtk_widget_set_size_request (adherant_button28, 74, 29);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (adherant_button28), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image30 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox28), image30, FALSE, FALSE, 0);

  label77 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox28), label77, FALSE, FALSE, 0);

  rdv_coach = gtk_label_new (_("rdv_coach"));
  gtk_widget_show (rdv_coach);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), rdv_coach);

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed18);

  adherant_label80 = gtk_label_new (_("Le planning des cours de la semaine:"));
  gtk_widget_show (adherant_label80);
  gtk_fixed_put (GTK_FIXED (fixed18), adherant_label80, -8, 8);
  gtk_widget_set_size_request (adherant_label80, 704, 16);
  gtk_label_set_use_markup (GTK_LABEL (adherant_label80), TRUE);

  adherant_treeview1 = gtk_tree_view_new ();
  gtk_widget_show (adherant_treeview1);
  gtk_fixed_put (GTK_FIXED (fixed18), adherant_treeview1, 128, 40);
  gtk_widget_set_size_request (adherant_treeview1, 456, 232);

  adherant_button29 = gtk_button_new ();
  gtk_widget_show (adherant_button29);
  gtk_fixed_put (GTK_FIXED (fixed18), adherant_button29, 24, 320);
  gtk_widget_set_size_request (adherant_button29, 106, 29);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (adherant_button29), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image31 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox29), image31, FALSE, FALSE, 0);

  label82 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label82);
  gtk_box_pack_start (GTK_BOX (hbox29), label82, FALSE, FALSE, 0);

  planning_cours = gtk_label_new (_("planning_cours"));
  gtk_widget_show (planning_cours);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 6), planning_cours);

  g_signal_connect ((gpointer) adherant_comboboxentry1, "changed",
                    G_CALLBACK (on_adherant_comboboxentry1_changed),
                    NULL);
  g_signal_connect ((gpointer) adherant_button13, "clicked",
                    G_CALLBACK (on_adherant_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_button14, "clicked",
                    G_CALLBACK (on_adherant_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_entry11, "delete_text",
                    G_CALLBACK (on_adherant_entry11_delete_text),
                    NULL);
  g_signal_connect ((gpointer) adherant_entry11, "insert_text",
                    G_CALLBACK (on_adherant_entry11_insert_text),
                    NULL);
  g_signal_connect ((gpointer) adherant_entry12, "insert_text",
                    G_CALLBACK (on_adherant_entry12_insert_text),
                    NULL);
  g_signal_connect ((gpointer) adherant_entry12, "delete_text",
                    G_CALLBACK (on_adherant_entry12_delete_text),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton4, "changed",
                    G_CALLBACK (on_adherant_spinbutton4_changed),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton5, "changed",
                    G_CALLBACK (on_adherant_spinbutton5_changed),
                    NULL);
  g_signal_connect ((gpointer) adherant_button15, "clicked",
                    G_CALLBACK (on_adherant_button15_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton6, "change_value",
                    G_CALLBACK (on_adherant_spinbutton6_change_value),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton7, "change_value",
                    G_CALLBACK (on_spinbutton7_change_value),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton8, "change_value",
                    G_CALLBACK (on_spinbutton8_change_value),
                    NULL);
  g_signal_connect ((gpointer) adherant_comboboxentry2, "changed",
                    G_CALLBACK (on_comboboxentry2_changed),
                    NULL);
  g_signal_connect ((gpointer) adherant_button17, "clicked",
                    G_CALLBACK (on_adherant_button17_clicked),
                    NULL);
  g_signal_connect ((gpointer) badherant_button18, "clicked",
                    G_CALLBACK (on_badherant_utton18_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_button19, "clicked",
                    G_CALLBACK (on_button19_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton9, "change_value",
                    G_CALLBACK (on_adherant_spinbutton9_change_value),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton10, "change_value",
                    G_CALLBACK (on_adherant_spinbutton10_change_value),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton11, "change_value",
                    G_CALLBACK (on_adherant_spinbutton11_change_value),
                    NULL);
  g_signal_connect ((gpointer) adherant_comboboxentry3, "changed",
                    G_CALLBACK (on_comboboxentry3_changed),
                    NULL);
  g_signal_connect ((gpointer) adherant_button20, "clicked",
                    G_CALLBACK (on_adherant_button20_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_button21, "clicked",
                    G_CALLBACK (on_button21_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_button22, "clicked",
                    G_CALLBACK (on_adherant_button22_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton12, "change_value",
                    G_CALLBACK (on_spinbutton12_change_value),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton13, "change_value",
                    G_CALLBACK (on_spinbutton13_change_value),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton14, "change_value",
                    G_CALLBACK (on_adherant_spinbutton14_change_value),
                    NULL);
  g_signal_connect ((gpointer) adherant_comboboxentry4, "changed",
                    G_CALLBACK (on_comboboxentry4_changed),
                    NULL);
  g_signal_connect ((gpointer) adherant_button23, "clicked",
                    G_CALLBACK (on_adherant_button23_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_button24, "clicked",
                    G_CALLBACK (on_adherant_button24_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_button25, "clicked",
                    G_CALLBACK (on_adherant_button25_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton15, "change_value",
                    G_CALLBACK (on_spinbutton15_change_value),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton16, "change_value",
                    G_CALLBACK (on_adherant_spinbutton16_change_value),
                    NULL);
  g_signal_connect ((gpointer) adherant_spinbutton17, "change_value",
                    G_CALLBACK (on_adherant_spinbutton17_change_value),
                    NULL);
  g_signal_connect ((gpointer) adherant_button26, "clicked",
                    G_CALLBACK (on_button26_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_button27, "clicked",
                    G_CALLBACK (on_adherant_button27_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_button28, "clicked",
                    G_CALLBACK (on_button28_clicked),
                    NULL);
  g_signal_connect ((gpointer) adherant_button29, "clicked",
                    G_CALLBACK (on_adherant_button29_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window4, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window4, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window4, espace_adherants, "espace_adherants");
  GLADE_HOOKUP_OBJECT (window4, adherant_comboboxentry1, "adherant_comboboxentry1");
  GLADE_HOOKUP_OBJECT (window4, rdv_adherant, "rdv_adherant");
  GLADE_HOOKUP_OBJECT (window4, consulter_cours_adherant, "consulter_cours_adherant");
  GLADE_HOOKUP_OBJECT (window4, adherant_button12, "adherant_button12");
  GLADE_HOOKUP_OBJECT (window4, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window4, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window4, image14, "image14");
  GLADE_HOOKUP_OBJECT (window4, label48, "label48");
  GLADE_HOOKUP_OBJECT (window4, inf_per_aderant, "inf_per_aderant");
  GLADE_HOOKUP_OBJECT (window4, adherant_button13, "adherant_button13");
  GLADE_HOOKUP_OBJECT (window4, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window4, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window4, image15, "image15");
  GLADE_HOOKUP_OBJECT (window4, label50, "label50");
  GLADE_HOOKUP_OBJECT (window4, adherant_button14, "adherant_button14");
  GLADE_HOOKUP_OBJECT (window4, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window4, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window4, image16, "image16");
  GLADE_HOOKUP_OBJECT (window4, label51, "label51");
  GLADE_HOOKUP_OBJECT (window4, espace_adherants, "espace_adherants");
  GLADE_HOOKUP_OBJECT (window4, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (window4, adherant_entry11, "adherant_entry11");
  GLADE_HOOKUP_OBJECT (window4, adherant_entry12, "adherant_entry12");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton4, "adherant_spinbutton4");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton5, "adherant_spinbutton5");
  GLADE_HOOKUP_OBJECT (window4, info_per, "info_per");
  GLADE_HOOKUP_OBJECT (window4, adherant_label53, "adherant_label53");
  GLADE_HOOKUP_OBJECT (window4, adherant_label54, "adherant_label54");
  GLADE_HOOKUP_OBJECT (window4, adherant_label55, "adherant_label55");
  GLADE_HOOKUP_OBJECT (window4, adherant_button15, "adherant_button15");
  GLADE_HOOKUP_OBJECT (window4, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window4, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window4, image17, "image17");
  GLADE_HOOKUP_OBJECT (window4, label56, "label56");
  GLADE_HOOKUP_OBJECT (window4, adherant_button16, "adherant_button16");
  GLADE_HOOKUP_OBJECT (window4, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window4, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window4, image18, "image18");
  GLADE_HOOKUP_OBJECT (window4, label57, "label57");
  GLADE_HOOKUP_OBJECT (window4, informations_personnelles, "informations_personnelles");
  GLADE_HOOKUP_OBJECT (window4, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton6, "adherant_spinbutton6");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton7, "adherant_spinbutton7");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton8, "adherant_spinbutton8");
  GLADE_HOOKUP_OBJECT (window4, adherant_label58, "adherant_label58");
  GLADE_HOOKUP_OBJECT (window4, adherant_label59, "adherant_label59");
  GLADE_HOOKUP_OBJECT (window4, adherant_comboboxentry2, "adherant_comboboxentry2");
  GLADE_HOOKUP_OBJECT (window4, adherant_button17, "adherant_button17");
  GLADE_HOOKUP_OBJECT (window4, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window4, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window4, image19, "image19");
  GLADE_HOOKUP_OBJECT (window4, label60, "label60");
  GLADE_HOOKUP_OBJECT (window4, badherant_button18, "badherant_button18");
  GLADE_HOOKUP_OBJECT (window4, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window4, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window4, image20, "image20");
  GLADE_HOOKUP_OBJECT (window4, label61, "label61");
  GLADE_HOOKUP_OBJECT (window4, adherant_button19, "adherant_button19");
  GLADE_HOOKUP_OBJECT (window4, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window4, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window4, image21, "image21");
  GLADE_HOOKUP_OBJECT (window4, label62, "label62");
  GLADE_HOOKUP_OBJECT (window4, rdv_med, "rdv_med");
  GLADE_HOOKUP_OBJECT (window4, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (window4, adherant_label64, "adherant_label64");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton9, "adherant_spinbutton9");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton10, "adherant_spinbutton10");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton11, "adherant_spinbutton11");
  GLADE_HOOKUP_OBJECT (window4, adherant_label63, "adherant_label63");
  GLADE_HOOKUP_OBJECT (window4, adherant_comboboxentry3, "adherant_comboboxentry3");
  GLADE_HOOKUP_OBJECT (window4, adherant_button20, "adherant_button20");
  GLADE_HOOKUP_OBJECT (window4, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window4, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window4, image22, "image22");
  GLADE_HOOKUP_OBJECT (window4, label65, "label65");
  GLADE_HOOKUP_OBJECT (window4, adherant_button21, "adherant_button21");
  GLADE_HOOKUP_OBJECT (window4, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window4, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window4, image23, "image23");
  GLADE_HOOKUP_OBJECT (window4, label66, "label66");
  GLADE_HOOKUP_OBJECT (window4, adherant_button22, "adherant_button22");
  GLADE_HOOKUP_OBJECT (window4, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window4, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window4, image24, "image24");
  GLADE_HOOKUP_OBJECT (window4, label67, "label67");
  GLADE_HOOKUP_OBJECT (window4, rdv_kine, "rdv_kine");
  GLADE_HOOKUP_OBJECT (window4, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton12, "adherant_spinbutton12");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton13, "adherant_spinbutton13");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton14, "adherant_spinbutton14");
  GLADE_HOOKUP_OBJECT (window4, adherant_label68, "adherant_label68");
  GLADE_HOOKUP_OBJECT (window4, adherant_label69, "adherant_label69");
  GLADE_HOOKUP_OBJECT (window4, adherant_comboboxentry4, "adherant_comboboxentry4");
  GLADE_HOOKUP_OBJECT (window4, adherant_button23, "adherant_button23");
  GLADE_HOOKUP_OBJECT (window4, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window4, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window4, image25, "image25");
  GLADE_HOOKUP_OBJECT (window4, label70, "label70");
  GLADE_HOOKUP_OBJECT (window4, adherant_button24, "adherant_button24");
  GLADE_HOOKUP_OBJECT (window4, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window4, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window4, image26, "image26");
  GLADE_HOOKUP_OBJECT (window4, label71, "label71");
  GLADE_HOOKUP_OBJECT (window4, adherant_button25, "adherant_button25");
  GLADE_HOOKUP_OBJECT (window4, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window4, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window4, image27, "image27");
  GLADE_HOOKUP_OBJECT (window4, label72, "label72");
  GLADE_HOOKUP_OBJECT (window4, rdv_diet, "rdv_diet");
  GLADE_HOOKUP_OBJECT (window4, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton15, "adherant_spinbutton15");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton16, "adherant_spinbutton16");
  GLADE_HOOKUP_OBJECT (window4, adherant_spinbutton17, "adherant_spinbutton17");
  GLADE_HOOKUP_OBJECT (window4, adherant_label73, "adherant_label73");
  GLADE_HOOKUP_OBJECT (window4, adherant_label74, "adherant_label74");
  GLADE_HOOKUP_OBJECT (window4, adherant_comboboxentry5, "adherant_comboboxentry5");
  GLADE_HOOKUP_OBJECT (window4, adherant_button26, "adherant_button26");
  GLADE_HOOKUP_OBJECT (window4, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window4, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (window4, image28, "image28");
  GLADE_HOOKUP_OBJECT (window4, label75, "label75");
  GLADE_HOOKUP_OBJECT (window4, adherant_button27, "adherant_button27");
  GLADE_HOOKUP_OBJECT (window4, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window4, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (window4, image29, "image29");
  GLADE_HOOKUP_OBJECT (window4, label76, "label76");
  GLADE_HOOKUP_OBJECT (window4, adherant_button28, "adherant_button28");
  GLADE_HOOKUP_OBJECT (window4, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window4, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (window4, image30, "image30");
  GLADE_HOOKUP_OBJECT (window4, label77, "label77");
  GLADE_HOOKUP_OBJECT (window4, rdv_coach, "rdv_coach");
  GLADE_HOOKUP_OBJECT (window4, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (window4, adherant_label80, "adherant_label80");
  GLADE_HOOKUP_OBJECT (window4, adherant_treeview1, "adherant_treeview1");
  GLADE_HOOKUP_OBJECT (window4, adherant_button29, "adherant_button29");
  GLADE_HOOKUP_OBJECT (window4, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window4, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (window4, image31, "image31");
  GLADE_HOOKUP_OBJECT (window4, label82, "label82");
  GLADE_HOOKUP_OBJECT (window4, planning_cours, "planning_cours");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed5;
  GtkWidget *label8;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));
  gtk_window_set_position (GTK_WINDOW (window5), GTK_WIN_POS_CENTER);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5), fixed5);

  label8 = gtk_label_new (_("Bienvenue dans l'espace kinesitherapeute"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed5), label8, 80, 128);
  gtk_widget_set_size_request (label8, 272, 64);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5, label8, "label8");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GtkWidget *fixed6;
  GtkWidget *label9;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("window6"));
  gtk_window_set_position (GTK_WINDOW (window6), GTK_WIN_POS_CENTER);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window6), fixed6);

  label9 = gtk_label_new (_("Bienvenue dans l'espace dieticien"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed6), label9, 88, 112);
  gtk_widget_set_size_request (label9, 193, 41);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window6, label9, "label9");

  return window6;
}

GtkWidget*
create_window7 (void)
{
  GtkWidget *window7;
  GtkWidget *fixed7;
  GtkWidget *button3;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label10;
  GtkWidget *button4;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label16;
  GtkWidget *label11;

  window7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7), _("window7"));
  gtk_window_set_position (GTK_WINDOW (window7), GTK_WIN_POS_CENTER);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window7), fixed7);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed7), button3, 344, 16);
  gtk_widget_set_size_request (button3, 80, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button3), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("logout"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox2), label10, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed7), button4, 128, 72);
  gtk_widget_set_size_request (button4, 192, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button4), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Gestion des comptes "));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox6), label16, FALSE, FALSE, 0);

  label11 = gtk_label_new (_("espace Admin"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed7), label11, 112, 16);
  gtk_widget_set_size_request (label11, 208, 32);

  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7, window7, "window7");
  GLADE_HOOKUP_OBJECT (window7, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window7, button3, "button3");
  GLADE_HOOKUP_OBJECT (window7, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window7, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window7, image2, "image2");
  GLADE_HOOKUP_OBJECT (window7, label10, "label10");
  GLADE_HOOKUP_OBJECT (window7, button4, "button4");
  GLADE_HOOKUP_OBJECT (window7, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window7, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window7, image6, "image6");
  GLADE_HOOKUP_OBJECT (window7, label16, "label16");
  GLADE_HOOKUP_OBJECT (window7, label11, "label11");

  return window7;
}

GtkWidget*
create_window8 (void)
{
  GtkWidget *window8;
  GtkWidget *fixed8;
  GtkWidget *label12;
  GtkWidget *button8;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image10;
  GtkWidget *label24;
  GtkWidget *button7;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label15;
  GtkWidget *button6;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label14;
  GtkWidget *button5;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label13;

  window8 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window8), _("window8"));
  gtk_window_set_position (GTK_WINDOW (window8), GTK_WIN_POS_CENTER);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window8), fixed8);

  label12 = gtk_label_new (_("gestion des comptes "));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed8), label12, 104, 8);
  gtk_widget_set_size_request (label12, 184, 40);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed8), button8, 144, 256);
  gtk_widget_set_size_request (button8, 112, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button8), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image10 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox8), image10, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox8), label24, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed8), button7, 144, 192);
  gtk_widget_set_size_request (button7, 112, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button7), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Supprimer "));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox5), label15, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed8), button6, 144, 120);
  gtk_widget_set_size_request (button6, 112, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button6), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-print-preview", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox4), label14, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed8), button5, 144, 56);
  gtk_widget_set_size_request (button5, 112, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button5), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Ajouter "));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox3), label13, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window8, window8, "window8");
  GLADE_HOOKUP_OBJECT (window8, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window8, label12, "label12");
  GLADE_HOOKUP_OBJECT (window8, button8, "button8");
  GLADE_HOOKUP_OBJECT (window8, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window8, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window8, image10, "image10");
  GLADE_HOOKUP_OBJECT (window8, label24, "label24");
  GLADE_HOOKUP_OBJECT (window8, button7, "button7");
  GLADE_HOOKUP_OBJECT (window8, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window8, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window8, image5, "image5");
  GLADE_HOOKUP_OBJECT (window8, label15, "label15");
  GLADE_HOOKUP_OBJECT (window8, button6, "button6");
  GLADE_HOOKUP_OBJECT (window8, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window8, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window8, image4, "image4");
  GLADE_HOOKUP_OBJECT (window8, label14, "label14");
  GLADE_HOOKUP_OBJECT (window8, button5, "button5");
  GLADE_HOOKUP_OBJECT (window8, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window8, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window8, image3, "image3");
  GLADE_HOOKUP_OBJECT (window8, label13, "label13");

  return window8;
}

GtkWidget*
create_window9 (void)
{
  GtkWidget *window9;
  GtkWidget *fixed9;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label19;
  GtkWidget *label18;
  GtkWidget *label26;
  GtkWidget *label32;
  GtkWidget *label27;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label17;
  GtkWidget *label33;
  GtkWidget *button9;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image11;
  GtkWidget *label34;
  GtkWidget *label25;
  GtkWidget *combobox1;
  GtkWidget *combobox2;
  GtkWidget *button11;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image13;
  GtkWidget *label36;

  window9 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window9), _("window9"));
  gtk_window_set_position (GTK_WINDOW (window9), GTK_WIN_POS_CENTER);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window9), fixed9);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed9), entry3, 192, 80);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed9), entry4, 192, 128);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry4), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed9), entry5, 192, 536);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed9), entry6, 192, 288);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed9), entry7, 192, 336);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label20 = gtk_label_new ("");
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed9), label20, 40, 184);
  gtk_widget_set_size_request (label20, 104, 32);

  label21 = gtk_label_new (_("Role"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed9), label21, 40, 176);
  gtk_widget_set_size_request (label21, 104, 32);

  label19 = gtk_label_new (_("password"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed9), label19, 40, 128);
  gtk_widget_set_size_request (label19, 104, 32);

  label18 = gtk_label_new (_("username"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed9), label18, 40, 80);
  gtk_widget_set_size_request (label18, 104, 32);

  label26 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed9), label26, 40, 328);
  gtk_widget_set_size_request (label26, 104, 32);

  label32 = gtk_label_new (_("N\302\260 du carte d'id"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed9), label32, 40, 408);
  gtk_widget_set_size_request (label32, 104, 32);

  label27 = gtk_label_new (_("Nom "));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed9), label27, 40, 288);
  gtk_widget_set_size_request (label27, 104, 32);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed9), entry8, 192, 376);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed9), entry9, 192, 416);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed9), entry10, 192, 496);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton1, 192, 456);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label28 = gtk_label_new (_("Role"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed9), label28, 40, 576);
  gtk_widget_set_size_request (label28, 104, 32);

  label29 = gtk_label_new (_("mail"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed9), label29, 40, 536);
  gtk_widget_set_size_request (label29, 104, 32);

  label30 = gtk_label_new (_("num de tel"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed9), label30, 40, 496);
  gtk_widget_set_size_request (label30, 104, 32);

  label31 = gtk_label_new (_("date_naissance"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed9), label31, 40, 456);
  gtk_widget_set_size_request (label31, 104, 32);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton2, 272, 456);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 1900, 2018, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton3, 360, 456);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label17 = gtk_label_new (_("Creation du compte "));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed9), label17, 144, 16);
  gtk_widget_set_size_request (label17, 192, 40);

  label33 = gtk_label_new (_("Saisie de donn\303\251s"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed9), label33, 152, 216);
  gtk_widget_set_size_request (label33, 192, 40);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed9), button9, 152, 624);
  gtk_widget_set_size_request (button9, 192, 56);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox9), image11, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Enregistrer "));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox9), label34, FALSE, FALSE, 0);

  label25 = gtk_label_new (_("username"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed9), label25, 40, 368);
  gtk_widget_set_size_request (label25, 104, 32);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox1, 150, 175);
  gtk_widget_set_size_request (combobox1, 200, 31);
  gtk_container_set_border_width (GTK_CONTAINER (combobox1), 201);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("coach"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("adherent"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("kine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("dieteticien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("nutritionniste"));

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox2, 152, 576);
  gtk_widget_set_size_request (combobox2, 200, 31);
  gtk_container_set_border_width (GTK_CONTAINER (combobox2), 201);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("coach"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("adherent"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("kine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("dieteticien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("nutritionniste"));

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed9), button11, 384, 696);
  gtk_widget_set_size_request (button11, 90, 45);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button11), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image13 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox11), image13, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("back"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox11), label36, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window9, window9, "window9");
  GLADE_HOOKUP_OBJECT (window9, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window9, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window9, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window9, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window9, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window9, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window9, label20, "label20");
  GLADE_HOOKUP_OBJECT (window9, label21, "label21");
  GLADE_HOOKUP_OBJECT (window9, label19, "label19");
  GLADE_HOOKUP_OBJECT (window9, label18, "label18");
  GLADE_HOOKUP_OBJECT (window9, label26, "label26");
  GLADE_HOOKUP_OBJECT (window9, label32, "label32");
  GLADE_HOOKUP_OBJECT (window9, label27, "label27");
  GLADE_HOOKUP_OBJECT (window9, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window9, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (window9, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (window9, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window9, label28, "label28");
  GLADE_HOOKUP_OBJECT (window9, label29, "label29");
  GLADE_HOOKUP_OBJECT (window9, label30, "label30");
  GLADE_HOOKUP_OBJECT (window9, label31, "label31");
  GLADE_HOOKUP_OBJECT (window9, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window9, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window9, label17, "label17");
  GLADE_HOOKUP_OBJECT (window9, label33, "label33");
  GLADE_HOOKUP_OBJECT (window9, button9, "button9");
  GLADE_HOOKUP_OBJECT (window9, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window9, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window9, image11, "image11");
  GLADE_HOOKUP_OBJECT (window9, label34, "label34");
  GLADE_HOOKUP_OBJECT (window9, label25, "label25");
  GLADE_HOOKUP_OBJECT (window9, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window9, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (window9, button11, "button11");
  GLADE_HOOKUP_OBJECT (window9, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window9, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window9, image13, "image13");
  GLADE_HOOKUP_OBJECT (window9, label36, "label36");

  return window9;
}

GtkWidget*
create_window10 (void)
{
  GtkWidget *window10;
  GtkWidget *fixed10;
  GtkWidget *textview1;
  GtkWidget *button10;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image12;
  GtkWidget *label35;

  window10 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window10), _("window10"));
  gtk_window_set_position (GTK_WINDOW (window10), GTK_WIN_POS_CENTER);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (window10), fixed10);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_fixed_put (GTK_FIXED (fixed10), textview1, 16, 16);
  gtk_widget_set_size_request (textview1, 248, 400);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed10), button10, 280, 128);
  gtk_widget_set_size_request (button10, 128, 96);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button10), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox10), image12, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Afficher "));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox10), label35, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window10, window10, "window10");
  GLADE_HOOKUP_OBJECT (window10, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window10, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (window10, button10, "button10");
  GLADE_HOOKUP_OBJECT (window10, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window10, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window10, image12, "image12");
  GLADE_HOOKUP_OBJECT (window10, label35, "label35");

  return window10;
}

