/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login (void);
GtkWidget* create_nutritonniste (void);
GtkWidget* create_coach (void);
GtkWidget* create_adherant (void);
GtkWidget* create_kine (void);
GtkWidget* create_diet (void);
GtkWidget* create_admin (void);
